# -*- coding: utf-8 -*-
# C.3 Stale-closed (automated) — no human reason on record
from _gen_C_util import R, T
ITEMS3 = [
 {'sec':'C.3','h':'vLLM LoRA adapter reload can reuse stale prefix-cache blocks — stale-closed, never fixed',
  'u':['S2-ABANDONED-4'],
  'c':'closed as `NOT_PLANNED` BY THE AUTOMATED STALE BOT — the closure reason is bot text, not a maintainer decision. A contributor offered to reproduce but no fix landed.',
  'q':[R('S2-ABANDONED-4')]},
 {'sec':'C.3','h':'vLLM hybrid (DFlash speculative) + prefix caching IndexError in `get_temporal_copy_spec` — stale-closed',
  'u':['S2-ABANDONED-5'],'c':'closed as `NOT_PLANNED` BY THE AUTOMATED STALE BOT — bot text only, no maintainer statement.',
  'q':[R('S2-ABANDONED-5')]},
 {'sec':'C.3','h':'vLLM `SimpleCPUOffloadConnector` + Hybrid KV Cache Manager block-pool exhaustion kills the engine — stale-closed',
  'u':['S2-ABANDONED-6'],
  'c':'closed as `NOT_PLANNED` BY THE AUTOMATED STALE BOT. The bot’s closing comment was not present in the retrieved payload for this issue; the quoted label description is what the page carries. The failure is an engine-killing assertion.',
  'q':[R('S2-ABANDONED-6')]},
 {'sec':'C.3','h':'vLLM per-request prefix-cache-token telemetry on OTel spans — stale-closed',
  'u':['S2-ABANDONED-7'],'c':'closed as `NOT_PLANNED` BY THE AUTOMATED STALE BOT — bot text only.',
  'q':[R('S2-ABANDONED-7')]},
 {'sec':'C.3','h':'vLLM RFC to support KV cache compaction / token dropping (FastGen, DuoAttention, H2O, attention sink) — stale-closed before it was revisited',
  'u':['S3-ABANDONED-1','S11-ABANDONED-29'],
  'c':'closed as `NOT_PLANNED` BY THE `github-actions` STALE BOT, not by a maintainer (ClosedEvent actor `github-actions`, labels `RFC` + `stale`). The human comments in the thread are the closest thing to a human reason, and they are not refusals.',
  'q':[R('S3-ABANDONED-1')]},
 {'sec':'C.3','h':'SGLang WLFU (weighted LFU) radix-cache eviction policy PR — stale-closed',
  'u':['S3-ABANDONED-5'],'c':'PR closed unmerged BY THE `github-actions` STALE BOT, not a human maintainer.',
  'q':[R('S3-ABANDONED-5')]},
 {'sec':'C.3','h':'SGLang T-LRU (Tail-Optimized LRU) cache eviction policy PR — stale-closed',
  'u':['S3-ABANDONED-6'],'c':'PR closed unmerged BY THE `github-actions` STALE BOT, not a human maintainer.',
  'q':[R('S3-ABANDONED-6')]},
 {'sec':'C.3','h':'SGLang Marconi eviction PR — stale-closed while still a draft',
  'u':['S3-ABANDONED-7'],'c':'PR closed unmerged BY THE `github-actions` STALE BOT, not a human maintainer; it was still a draft.',
  'q':[R('S3-ABANDONED-7')]},
 {'sec':'C.3','h':'SGLang fix for SLRU’s burst distortion and stale-hot-prefix stagnation (a shipped policy’s known failure mode) — stale-closed unfixed',
  'u':['S3-ABANDONED-9'],
  'c':'PR closed unmerged BY THE `github-actions` STALE BOT, not a human maintainer. The shipped `slru` policy keeps the defect the PR described.',
  'q':[R('S3-ABANDONED-9')]},
 {'sec':'C.3','h':'vLLM phase-aware (think-phase vs answer-phase) KV cache quantisation — stale-closed despite a measured 58% KL reduction',
  'u':['S4-ABANDONED-12','S11-ABANDONED-28'],
  'c':'closed as not planned BY THE STALE BOT (GitHub Actions), NOT by a maintainer — no human maintainer reason exists on the page. The author’s own measured result is in the body.',
  'q':[R('S4-ABANDONED-12'),T('I have published a paper with a closed-form theorem and empirical validation showing this approach cuts attention KL divergence by **58%** compared to uniform 3-bit quantization on DeepSeek-R1-Distill-1.5B, with no additional inference-time compute.')],
  'qlab':['the author’s own measured claim, from the same issue body as relayed by the S11 row']},
 {'sec':'C.3','h':'Dynamic Memory Compression (DMC) for vLLM — maintainer pushback on the retrofit-data cost, then stale-closed (two duplicate requests)',
  'u':['S6-ABANDONED-1','S6-ABANDONED-2'],
  'c':'closed as `not_planned`; the visible close action was performed by the automation bot, not a human. A human maintainer objection precedes it on the first issue; the second (duplicate) issue has no maintainer reason on the page at all.',
  'q':[R('S6-ABANDONED-1'),R('S6-ABANDONED-2')],
  'qlab':['the duplicate request #4728, where only bot text exists'],
  'd':'#3549 created 2024-03-21, bot-closed 2025-01-02; #4728 created 2024-05-10, bot-closed 2024-11-27'},
 {'sec':'C.3','h':'vLLM LoRA adapters on DeepSeek-V2 have no effect (later diagnosed as the MLA `kv_b_proj` path) — stale-closed undiagnosed, re-filed ~15 months later',
  'u':['S6-ABANDONED-9'],
  'c':'stale-closed BY THE AUTOMATION BOT ONLY — no maintainer reason on the page. The later issue #48974 characterises it as unresolved. (Verifier note: the page for #17155 never mentions `kv_b_proj`, MLA or absorption; that mechanism comes from the later diagnosis.)',
  'q':[R('S6-ABANDONED-9')]},
 {'sec':'C.3','h':'Attention-sink support in MLA — requested, never implemented, stale-closed',
  'u':['S6-ABANDONED-10'],
  'c':'closed as `not_planned`; the only closure text is the automation bot’s — no human maintainer reason appears on the retrieved page.',
  'q':[R('S6-ABANDONED-10')]},
 {'sec':'C.3','h':'vLLM FA4 MLA decode backend — requested, a volunteer offered to do it, never landed, stale-closed',
  'u':['S6-ABANDONED-12'],
  'c':'closed as `not_planned`; the closure text is automation-bot only — no maintainer reason on the retrieved page. The community volunteer’s offer got no maintainer response before the bot closed it. VERIFIER CORRECTION: the page says “should remain open”, not “should still be open”.',
  'q':[R('S6-ABANDONED-12')]},
 {'sec':'C.3','h':'BFLA — a training-free sparse prefill attention backend offered for upstreaming to vLLM — stale-closed',
  'u':['S8-ABANDONED-1'],
  'c':'closed as `NOT_PLANNED` BY THE AUTOMATED STALE BOT, NOT by a maintainer — the only closure text is bot text. This must not be read as a maintainer rejection.',
  'q':[R('S8-ABANDONED-1')]},
 {'sec':'C.3','h':'vLLM frequency- and cost-aware prefix-cache eviction RFC and its implementation PR — both stale-closed',
  'u':['S9-ABANDONED-6'],
  'c':'issue closed as `NOT_PLANNED` BY THE AUTOMATED STALE BOT (`github-actions`), NOT by a maintainer; the linked implementation PR #27539 was closed by the same stale bot.',
  'q':[R('S9-ABANDONED-6')]},
 {'sec':'C.3','h':'vLLM workload-aware KV cache eviction policy PR — stale-closed unmerged',
  'u':['S9-ABANDONED-7'],
  'c':'PR closed unmerged BY THE AUTOMATED STALE BOT (`github-actions`), NOT by a maintainer; labels included `stale` and `needs-rebase`.',
  'q':[R('S9-ABANDONED-7')]},
 {'sec':'C.3','h':'vLLM changing `kv_load_failure_policy` default from “recompute” to “fail” — maintainers agreed, then the stale bot closed it',
  'u':['S10-ABANDONED-3'],
  'c':'closed as `NOT_PLANNED`, and the only closure text is automated stale-bot text, not a maintainer decision.',
  'q':[R('S10-ABANDONED-3')]},
 {'sec':'C.3','h':'vLLM NIXL connector silently disabling HMA — stale-closed; the duplicate/closure framing in the evidence file is unsupported',
  'u':['S10-ABANDONED-4'],
  'c':'VERIFIER CORRECTED: the issue was stale-closed by `github-actions` on 2026-09-12 (`duplicateOf: null`), NOT closed as a duplicate on 2026-08-08 (that date is the stale warning). The quoted comment is by contributor `chfeng-cs`, the author of the merged PR it cites — not a maintainer and not the closure reason. Downgraded to TITLE ONLY.',
  'e':'TITLE ONLY (verifier downgrade)'},
 {'sec':'C.3','h':'vLLM NIXL telemetry throughput not accounting for transfer overlapping — stale-closed with no answer from the pinged maintainer',
  'u':['S10-ABANDONED-5'],
  'c':'closed as `NOT_PLANNED`; the closure text is automated stale-bot text only — no human closure reason exists on the page.',
  'q':[R('S10-ABANDONED-5')]},
 {'sec':'C.3','h':'vLLM P2P NCCL XpYd prefill worker crash — stale-closed with the fix still unlocated',
  'u':['S10-ABANDONED-6'],
  'c':'closed as `NOT_PLANNED`; the closure text is automated stale-bot text only. VERIFIER CORRECTION: the evidence file’s date line was internally impossible; the real timeline is created 2025-09-17, human comments 2025-09-21 → 2025-10-15, stale label 2026-01-15, stale-closed 2026-02-15.',
  'q':[R('S10-ABANDONED-6')],
  'd':'created 2025-09-17, stale 2026-01-15, closed 2026-02-15 (verifier-corrected)'},
 {'sec':'C.3','h':'NVIDIA Dynamo heterogeneous-TP P/D in the SGLang path crashed on the recommended configuration — stale-closed',
  'u':['S10-ABANDONED-7'],'c':'closed as `NOT_PLANNED`; the closure text is automated inactivity text only.',
  'q':[R('S10-ABANDONED-7')]},
 {'sec':'C.3','h':'Dynamo KVBM silently provided no benefit unless an undocumented flag was set — stale-closed, negative result left in the body',
  'u':['S11-ABANDONED-10'],
  'c':'closed as not planned — AUTOMATED STALE-BOT CLOSURE, not a maintainer decision. The negative result is in the issue body, not the closure.',
  'q':[R('S11-ABANDONED-10')]},
 {'sec':'C.3','h':'Dynamo KVBM disk reads issued as many small 32 KB IOs instead of one contiguous 2 MB transfer — closed by an automation',
  'u':['S11-ABANDONED-12'],
  'c':'`state_reason=COMPLETED` but closed by an automation (`linear[bot]`), not a human; the last human comment asking “Did you resolve this? Thanks” went unanswered.',
  'q':[R('S11-ABANDONED-12')]},
 {'sec':'C.3','h':'Dynamo KVBM TTFT degradation with MTP — stale-closed, no human closure reason',
  'u':['S11-ABANDONED-13'],
  'c':'closed as not planned — AUTOMATED STALE-BOT CLOSURE (ClosedEvent actor `github-actions`); the quoted fragment is the reported symptom, not a closure statement.',
  'q':[R('S11-ABANDONED-13')]},
 {'sec':'C.3','h':'LMCache + Mooncake on a single node gave no benefit — stale-closed with the negative result unrebutted',
  'u':['S11-ABANDONED-22'],
  'c':'closed as not planned — AUTOMATED STALE-BOT CLOSURE. The substantive negative result is the reporter’s and the maintainer’s, not the closure text.',
  'q':[R('S11-ABANDONED-22')]},
 {'sec':'C.3','h':'vLLM selective KV cache offload (send part of the prompt to slower storage) — stale-closed after a maintainer redirect',
  'u':['S11-ABANDONED-26'],
  'c':'closed as not planned — AUTOMATED STALE-BOT CLOSURE, with a substantive maintainer-side redirect earlier in the thread.',
  'q':[R('S11-ABANDONED-26')]},
 {'sec':'C.3','h':'vLLM topology-aware KV cache compression proposal — stale-closed with no maintainer reason',
  'u':['S11-ABANDONED-27'],
  'c':'closed as not planned — AUTOMATED STALE-BOT CLOSURE. The only substantive technical reason on the page is a commenter’s, not a maintainer’s.',
  'q':[T("DeepSeek-V3's MLA compresses KV at the architecture level by using a shared latent vector. The residual KV cache is already smaller, so external compression may have diminishing returns. Worth benchmarking whether the gain is meaningful post-MLA vs. standard MHA models.")]},
 {'sec':'C.3','h':'vLLM KV-cache rollback / “step back” API in the engine core — maintainer rejection in-thread, then stale closure',
  'u':['S11-ABANDONED-30'],
  'c':'closed as not planned — AUTOMATED STALE-BOT CLOSURE after a maintainer rejection in-thread. The quoted maintainer sentence reproduces the page exactly, including its apparent typo.',
  'q':[R('S11-ABANDONED-30')]},
 {'sec':'C.3','h':'llama.cpp q4_0 symmetric KV cache performance regression — not reproduced; stale-closed',
  'u':['S11-ABANDONED-34'],
  'c':'closed as not planned — AUTOMATED STALE-BOT CLOSURE.',
  'q':[R('S11-ABANDONED-34')]},
 {'sec':'C.3','h':'llama.cpp KV cache in the RPC backend — the prompt cache does no useful work and its save path aborts the server; stale-closed',
  'u':['S11-ABANDONED-47'],'c':'closed as not planned — AUTOMATED STALE-BOT CLOSURE.',
  'q':[R('S11-ABANDONED-47')]},
 {'sec':'C.3','h':'llama.cpp cross-request caching gives no benefit on SWA models (always invalidated) — stale-closed',
  'u':['S11-ABANDONED-48'],'c':'closed as not planned — AUTOMATED STALE-BOT CLOSURE.',
  'q':[R('S11-ABANDONED-48')]},
 {'sec':'C.3','h':'TensorRT-LLM `enable_block_reuse=True` crash on Gemma 3 VSWA — stale-closed, never refuted',
  'u':['S11-ABANDONED-57'],
  'c':'closed as not planned — AUTOMATED STALE-BOT CLOSURE, not a maintainer decision. A maintainer did post a genuine reproduction attempt (Gemma-3-1b on RTX PRO 6000 Blackwell) before the issue went stale, i.e. the bug timed out rather than being refuted.',
  'q':[T('Issue has not received an update in over 14 days. Adding stale label.'),T('This issue was closed because it has been 14 days without activity since it has been marked as stale.')],
  'qlab':['the stale-bot closing text on the same page']},
 {'sec':'C.3','h':'vLLM Prefill Context Parallel (PCP) for MLA models — full review cycle, then stale-closed',
  'u':['S12-ABANDONED-1'],
  'c':'closed as not planned by the STALE BOT (ClosedEvent actor `github-actions Bot`), not by a maintainer — the substantive human blockers are quoted below but no maintainer closing statement exists.',
  'q':[R('S12-ABANDONED-1')]},
 {'sec':'C.3','h':'vLLM Prefill Context Parallel for GQA FlashInfer (split-out follow-up, plus its predecessor) — stale-closed unmerged',
  'u':['S12-ABANDONED-2','S12-ABANDONED-10'],
  'c':'#28723 closed unmerged by the STALE BOT (no “not planned” badge, no human reason); its predecessor #26864 — which carries the authors’ own negative GQA+PCP measurement — was closed unmerged earlier.',
  'q':[R('S12-ABANDONED-2'),R('S12-ABANDONED-10')],
  'qlab':['the predecessor PR #26864, where the technique’s own measurement is the reason it could not be justified as a default'],
  'd':'#28723 created 2025-11-14, closed 2026-04-01; #26864 created 2025-10-15, closed 2025-11-20'},
 {'sec':'C.3','h':'vLLM NCCL graph-mixing optimisation for context parallel (~1 ms TPOT win) — stale-closed unmerged',
  'u':['S12-ABANDONED-4'],
  'c':'PR closed unmerged by the STALE BOT; no maintainer closing comment exists — the only closure reason is bot text.',
  'q':[R('S12-ABANDONED-4')]},
 {'sec':'C.3','h':'vLLM Decode Context Parallel failed to run on H200 — stale-closed, never resolved',
  'u':['S12-ABANDONED-6'],
  'c':'closed as `NOT_PLANNED` by the STALE BOT — no maintainer reason statement, only bot text.',
  'q':[R('S12-ABANDONED-6')]},
 {'sec':'C.3','h':'vLLM DCP regression between v0.10.2 and v0.11.0 for DeepSeek-R1 — stale-closed, never root-caused',
  'u':['S12-ABANDONED-7'],'c':'closed as `NOT_PLANNED` by the STALE BOT only — explicitly not a maintainer decision.',
  'q':[R('S12-ABANDONED-7')]},
 {'sec':'C.3','h':'vLLM FP8 KV cache + DCP for MLA, benchmarked on 8× and 16× RTX PRO 6000 — stale-closed unmerged',
  'u':['S12-ABANDONED-9'],'c':'closed as not planned by the STALE BOT; no human maintainer closing reason — explicitly bot-driven.',
  'q':[R('S12-ABANDONED-9')]},
 {'sec':'C.3','h':'SGLang context-parallel PRs — one produced incorrect long-context output, one was an unmaintained draft; both stale-closed',
  'u':['S12-ABANDONED-18','S12-ABANDONED-19'],
  'c':'both PRs closed unmerged by the STALE BOT; closure reason is bot text only in each case. Both rows are TITLE ONLY in the evidence.',
  'q':[R('S12-ABANDONED-18'),R('S12-ABANDONED-19')],
  'qlab':['the second PR (#21865), closed as an unmaintained draft'],
  'e':'TITLE ONLY'},
 {'sec':'C.3','h':'vLLM T-LRU conversation-aware KV cache eviction RFC — stale-closed; NOT a maintainer decision',
  'u':['S13-ABANDONED-8'],
  'c':'closed as `NOT_PLANNED` BY THE AUTOMATED STALE BOT — there is NO human maintainer reason on the page. Do not read this as a maintainer decision.',
  'q':[R('S13-ABANDONED-8')]},
 {'sec':'C.3','h':'vLLM caching system-prompt token ids (to skip re-tokenisation) — stale-closed',
  'u':['S13-ABANDONED-9'],
  'c':'closed as `NOT_PLANNED` with labels `performance` and `stale`, BY THE AUTOMATED STALE BOT — no human maintainer reason on the page.',
  'q':[R('S13-ABANDONED-9')]},
 {'sec':'C.3','h':'vLLM hybrid checkpoint ABI for non-KV prefix resume (RFC) — stale-closed',
  'u':['S13-ABANDONED-11'],
  'c':'closed as `NOT_PLANNED` with the `stale` label, BY THE AUTOMATED STALE BOT — no human maintainer reason on the page.',
  'q':[R('S13-ABANDONED-11')]},
 {'sec':'C.3','h':'vLLM potential use-after-free in the KV block allocator under eviction pressure — stale-closed while the candidate fix PR remains open',
  'u':['S14-ABANDONED-7'],
  'c':'closed as `NOT_PLANNED` by `github-actions` (stale automation), NOT by a maintainer. The candidate fix PR #37164 is still OPEN and unmerged.',
  'q':[R('S14-ABANDONED-7')]},
 {'sec':'C.3','h':'vLLM stats metric for `available_kv_cache_memory` — stale-closed unanswered',
  'u':['S14-ABANDONED-8'],
  'c':'closed as `NOT_PLANNED`, label `stale`, by `github-actions` (stale automation), NOT by a maintainer.',
  'q':[R('S14-ABANDONED-8')]},
]
