# -*- coding: utf-8 -*-
# C.2 wontfix / not-planned / by-design / out-of-scope closures
from _gen_C_util import R, T
ITEMS2 = [
 {'sec':'C.2','h':'vLLM align-mode checkpoint retention visibility — author-closed as redundant, not a maintainer rejection',
  'u':['S1-ABANDONED-3','S2-ABANDONED-2'],
  'c':'closed as not planned (`stateReason=NOT_PLANNED`) by the author himself; explicitly not a stale-bot closure and not a maintainer rejection. The report was folded into the fix PR #53596.',
  'q':[R('S1-ABANDONED-3'),R('S2-ABANDONED-2')],
  'qlab':['the same closing comment, with the follow-up line']},
 {'sec':'C.2','h':'Sizing the SGLang hybrid Mamba state pool from explicit `max_running_requests` — marked not planned',
  'u':['S1-ABANDONED-4'],
  'c':'closed as not planned by a maintainer (`huangzhilin-hzl`) on the day of filing. The maintainer’s own stated reason is NOT present in the retrieved payload; the only rationale text on the page is the reporter’s reaction.',
  'q':[T("I am disappointed that this issue was marked as 'not planned'.")]},
 {'sec':'C.2','h':'Naive round-robin block allocation for sliding-window layers — deliberately designed out of the shipped hybrid KV manager',
  'u':['S1-ABANDONED-6'],
  'c':'by design — considered and deliberately not adopted in the shipped vLLM hybrid KV cache design doc; a closed design decision, not a merged feature.',
  'q':[R('S1-ABANDONED-6')]},
 {'sec':'C.2','h':'Cache-affinity-aware request ordering in the vLLM V1 scheduler (`CacheAffinityScheduler`) — dropped after the +7.4% result was shown to be a benchmark artefact',
  'u':['S2-ABANDONED-1','S11-ABANDONED-1','S13-ABANDONED-10','S7-ABANDONED-1'],
  'c':'closed as not planned (`stateReason=NOT_PLANNED`). VERIFIER CORRECTION: the closer was the human RFC author `kliukovkin`, who posted a closing comment — NOT the stale bot and not a maintainer. The stale label/notice is genuinely present but is only a notice. The evidence file’s “the closure actor is the stale bot / no human reason exists” is false.',
  'q':[R('S2-ABANDONED-1')],
  'w':'`kliukovkin` (vLLM contributor), RFC #42185 / CacheAffinityScheduler plugin; also mirrored as S7-ABANDONED-1, S11-ABANDONED-1 and S13-ABANDONED-10',
  'd':'created 2026-05-09, closed 2026-08-18 (ClosedEvent 2026-08-18T00:44:01Z by kliukovkin)'},
 {'sec':'C.2','h':'Sparse KV cache management framework RFC — closed “COMPLETED” while labelled stale, with only one of four tasks delivered',
  'u':['S3-ABANDONED-4'],
  'c':'`state=CLOSED`, `stateReason=COMPLETED`, labels include `RFC` and `stale`. No human ClosedEvent or explanatory comment was found; the only merged artifact (PR #12608) covers task (1) of four, and the CachePolicy interface for H2O/FastGen does not exist in the tree today. Treat “COMPLETED” as not substantiated for the eviction-policy content.',
  'q':[R('S3-ABANDONED-4')]},
 {'sec':'C.2','h':'vLLM shipped TurboQuant backend drops QJL by design and needs a boundary-layer crutch for its aggressive presets',
  'u':['S4-ABANDONED-1','S4-ABANDONED-18'],
  'c':'by design in shipped code — QJL is documented as deliberately omitted, and the aggressive presets are documented as requiring an empirical crutch (boundary-layer skipping).',
  'q':[R('S4-ABANDONED-1'),R('S4-ABANDONED-18')],
  'qlab':['the second abandonment recorded in the same shipped file']},
 {'sec':'C.2','h':'QJL error correction (Algorithm 2) omitted from a second, independent TurboQuant implementation',
  'u':['S4-ABANDONED-10'],
  'c':'omitted by design in an independent implementation — corroborates the vLLM TurboQuant omission. VERIFIER CORRECTION: these words were posted by `Aaryan-Kapoor` and `veritatisquaesitoressumus`, not by `TheTom`.',
  'w':'`Aaryan-Kapoor` and `veritatisquaesitoressumus`, in the ggml-org/llama.cpp discussion #20969 (verifier-corrected authorship; the evidence file attributed these words to TheTom)',
  'q':[R('S4-ABANDONED-10')]},
 {'sec':'C.2','h':'Direct GPU↔storage access (GPUDirect Storage / GPU-GPU) — explicitly excluded from vLLM’s multi-tier offloading design',
  'u':['S5-ABANDONED-3'],
  'c':'by design — an explicit “What we don’t intend to support” section in a maintainer-authored RFC; the shipped tiering implementation carries exactly this restriction.',
  'q':[R('S5-ABANDONED-3')]},
 {'sec':'C.2','h':'MLA’s low-communication “absorb” form for training — hard-banned by Megatron-Core and measured to regress activation memory',
  'u':['S6-ABANDONED-3'],
  'c':'by design — a hard assertion in shipped library code disables the technique with no documented reason; the accompanying paper explains why the ban is well-founded (20–34% activation-memory regression when ported to training).',
  'q':[R('S6-ABANDONED-3')]},
 {'sec':'C.2','h':'LMCache CacheBlend: blend store cannot be disabled and has no size cap',
  'u':['S7-ABANDONED-4','S7-ABANDONED-3','S11-ABANDONED-21'],
  'c':'both issues closed as not planned (`stateReason: NOT_PLANNED`). VERIFIER CORRECTION: each page carries a comment “Closing here” plus a ClosedEvent whose actor is the issue author `shawnguyen-tensormesh`; the evidence file’s repeated claim that comment text does not exist and the actor is unidentifiable is false for all six CacheBlend issues.',
  'q':[R('S11-ABANDONED-21')],
  'w':'`shawnguyen-tensormesh` (LMCache), issues #4665 and #4664 (the two topics were filed together by the same author)',
  'd':'both created 2026-08-20, closed 2026-08-21 by the author (“Closing here”)'},
 {'sec':'C.2','h':'LMCache CacheBlend: no per-model correctness gate for the blend re-RoPE approximation',
  'u':['S7-ABANDONED-5','S11-ABANDONED-20'],
  'c':'closed as not planned (`stateReason: NOT_PLANNED`) by the issue author, whose only closure comment is “Closing here” (verifier-corrected: the evidence file claimed no comment text and no identifiable actor).',
  'w':'`shawnguyen-tensormesh` (LMCache), issue #4666',
  'q':[R('S11-ABANDONED-20')]},
 {'sec':'C.2','h':'LMCache CacheBlend: missing inter-document padding for non-prefix reuse (~11% measured seam loss)',
  'u':['S7-ABANDONED-6'],
  'c':'closed as not planned by the issue author (comment: “Closing here”) — a measured seam tax was reported and not acted on.',
  'q':[T('Closing here')]},
 {'sec':'C.2','h':'LMCache cross-pod (cross-replica) sibling KV reuse — works, but is transient; closed as not planned',
  'u':['S7-ABANDONED-7'],
  'c':'closed as not planned by the issue author (comment: “Closing here”). The capability itself was reported to exist, but as a burst rather than steady state.',
  'q':[T('Closing here')]},
 {'sec':'C.2','h':'KV reuse across LoRA adapters — deliberately excluded by vLLM’s prefix-cache block-hash key',
  'u':['S7-ABANDONED-9'],
  'c':'not a closure — “by design”. vLLM folds the LoRA adapter name into the block hash, so two adapters can never hit each other’s cached blocks; an adapter change invalidates the chain from that point. Reinforced by security PR #54342 (TITLE ONLY).',
  'q':[R('S7-ABANDONED-9')]},
 {'sec':'C.2','h':'vLLM `kv_role='+chr(39)+'kv_both'+chr(39)+'` for NixlConnector — deprecated and scheduled for removal',
  'u':['S7-ABANDONED-10'],
  'c':'shipped deprecation warning in code (“will be removed in a future release”); the recommended usage was removed from the docs (PR #55693, CLOSED). Not yet deleted.',
  'q':[R('S7-ABANDONED-10')]},
 {'sec':'C.2','h':'vLLM uneven decode context parallelism for heterogeneous TP ranks — explicit maintainer scope rejection',
  'u':['S8-ABANDONED-4'],
  'c':'closed unmerged by a human maintainer (`hmellor`) as out of scope in-tree — a clean maintainer “no”, not a stale bot.',
  'q':[R('S8-ABANDONED-4')]},
 {'sec':'C.2','h':'TurboQuant KV cache + long-context chunked prefill — a workspace ratio that cannot be tuned around; reporter-closed as duplicate',
  'u':['S8-ABANDONED-8'],
  'c':'closed as not planned (`stateReason: NOT_PLANNED`) by the reporter themselves as a duplicate — not a maintainer rejection. The live siblings #41565 and #43357 remain open.',
  'q':[R('S8-ABANDONED-8')],
  'd':'created 2026-06-25; closed by the reporter'},
 {'sec':'C.2','h':'Avoiding recomputation of the last-token hidden states for spec decoding — declined in-thread as not worth the complexity',
  'u':['S10-ABANDONED-8'],
  'c':'closed as completed, but the requested generalisation was declined in-thread by a maintainer; the shipped artifact is a different, narrower debug connector.',
  'q':[R('S10-ABANDONED-8')]},
 {'sec':'C.2','h':'Dynamo KVBM disk→device onboarding (and KVBM itself) — closed as no longer supported',
  'u':['S11-ABANDONED-2','S11-ABANDONED-7'],
  'c':'closed as not planned by a human maintainer (`jthomson04`). A scope/support decision, not confirmation that the reported disk-onboarding performance problem is fixed. The companion PR #13184 was closed without merging; the verifier retrieved a fuller direct closure comment on the PR itself.',
  'q':[R('S11-ABANDONED-2'),T('Closing without merge because KVBM is no longer supported. The corresponding issue #12750 has been closed as not planned; this is a support/scope decision, not a claim that the layout or performance problem was fixed.')],
  'qlab':['the PR #13184 closure comment itself (verifier-retrieved, replacing the cross-reference)'],
  'd':'#12750 created 2026-08-06, closed 2026-09-10; PR #13184 created 2026-08-13, closed 2026-09-10'},
 {'sec':'C.2','h':'Dynamo KVBM lifecycle bug — second independent confirmation of the KVBM support removal',
  'u':['S11-ABANDONED-3'],
  'c':'closed as not planned by a human maintainer (`jthomson04`); a distinct closure text from #12750’s (different PR #13297, different bug), produced from the same template.',
  'q':[R('S11-ABANDONED-3')]},
 {'sec':'C.2','h':'Dynamo KVBM GPU HBM hit-rate exposure — closed with an explicit apology and rationale',
  'u':['S11-ABANDONED-4'],
  'c':'closed as not planned by a human maintainer (`dagil-nvidia`) — a deliberate “we would rather close than leave you hanging”.',
  'q':[R('S11-ABANDONED-4')]},
 {'sec':'C.2','h':'Dynamo KVBM documentation — “feature is being sunset”; docs re-add explicitly not planned',
  'u':['S11-ABANDONED-5'],
  'c':'documentation removal merged; KVBM deprecation announced in the catalog entry. Not yet deleted from the tree.',
  'q':[R('S11-ABANDONED-5')]},
 {'sec':'C.2','h':'Dynamo host-tier KV mirroring, offload and storage APIs — closed as superseded/deferred',
  'u':['S11-ABANDONED-8'],
  'c':'closed as not planned / superseded-deferred by a human contributor (`hutm`).',
  'q':[R('S11-ABANDONED-8')]},
 {'sec':'C.2','h':'Dynamo GMS-managed KV umbrella retired — the SGLang, TRT-LLM, host/storage, router/P2P, TP=2 and Kubernetes scopes dropped from the MVP',
  'u':['S11-ABANDONED-9'],
  'c':'closed as not planned by a human contributor (`hutm`); all 18 still-open PRs from the umbrella were closed without deleting their branches.',
  'q':[R('S11-ABANDONED-9')]},
 {'sec':'C.2','h':'llama.cpp DeepSeek-V4 prefix caching reprocesses the full prompt — closed not planned two days after the last comment',
  'u':['S11-ABANDONED-32'],
  'c':'closed `not_planned` by a human contributor (`am17an`) — not a stale-bot closure (no stale label), though no explicit “won’t fix” sentence was retrieved.',
  'q':[R('S11-ABANDONED-32')]},
 {'sec':'C.2','h':'llama.cpp canonical KV/long-context performance boundary — maintainers decline to invest in synthetic benchmarking',
  'u':['S11-ABANDONED-33'],
  'c':'closed `not_planned`. The retrieved page’s timeline was paginated and did not contain the ClosedEvent, so the closer cannot be named; the quoted maintainer statements are the reason on record.',
  'q':[R('S11-ABANDONED-33')]},
 {'sec':'C.2','h':'SGLang HiCache host hits returned stale MoE sidecar data — closed not planned, with the fix pursued elsewhere',
  'u':['S11-ABANDONED-49'],
  'c':'closed `NOT_PLANNED` (2026-07-10) after a human root-cause comment. VERIFIER CORRECTION: the evidence file’s “guard PR #27067 shipped instead of the fix” conclusion is UNSUPPORTED — #27067 is itself the migration FIX (`fix(hicache): migrate captured indexer-topk on host-tier cache hits`), closed unmerged on 2026-06-05 as superseded by #27326. The verifier downgrades this row to READ BODY with the conclusion unsupported.',
  'e':'READ BODY (verifier downgrade: conclusion UNSUPPORTED)'},
 {'sec':'C.2','h':'TensorRT-LLM reusing KV cache across different LoRAs — maintainer “not planned”',
  'u':['S11-ABANDONED-55'],
  'c':'closed as not planned by a maintainer (`karljang`) — a direct maintainer “no” in that repository’s KV-reuse space. (The typo `apprach` and the double space are in the original.)',
  'q':[R('S11-ABANDONED-55')]},
 {'sec':'C.2','h':'vLLM pipeline parallelism halves the usable KV block budget — answered by a maintainer as by-design',
  'u':['S12-ABANDONED-8'],
  'c':'closed as not planned by the stale bot AFTER a substantive maintainer answer; the maintainer’s “this is expected behaviour / the halving is fundamental” statement is the real human reason.',
  'q':[R('S12-ABANDONED-8')]},
]
