# -*- coding: utf-8 -*-
# C.1 Closed-unmerged pull requests
from _gen_C_util import R, T
ITEMS1 = [
 {'sec':'C.1','h':'vLLM `[Core] Cache policy framework` — the `CachePolicy` eviction abstraction for V0, closed unmerged',
  'u':['S3-ABANDONED-2'],'c':'PR closed unmerged by a named human maintainer (`hmellor`, vLLM Member), not a bot.',
  'q':[R('S3-ABANDONED-2')]},
 {'sec':'C.1','h':'vLLM `[Core] Support sparse KV cache framework` — H2O/SnapKV/Scissorhands/StreamingLLM eviction framework',
  'u':['S3-ABANDONED-3'],'c':'PR closed unmerged by a named human maintainer (`hmellor`); the RFC it implements (#5751) stays open.',
  'q':[R('S3-ABANDONED-3')]},
 {'sec':'C.1','h':'SGLang `[Feature] Semantic eviction for radix cache` — agent-workload reset/summarisation pruning',
  'u':['S3-ABANDONED-8','S13-ABANDONED-19'],
  'c':'PR closed unmerged by a human Collaborator (`hnyls2002`); the semantic-event path was never added to main.',
  'q':[R('S3-ABANDONED-8')],
  'd':'created 2026-03-07, closed 2026-08-10 (the S13 duplicate row for the same PR had no separable closure)',
  'qlab':[]},
 {'sec':'C.1','h':'SGLang TurboQuant KV-cache PR — closed unmerged as one of three concurrent proposals',
  'u':['S4-ABANDONED-3'],'c':'closed unmerged by a human collaborator, consolidating on #21419 (itself still open).',
  'q':[R('S4-ABANDONED-3')]},
 {'sec':'C.1','h':'vLLM Triton INT4 / INT2 per-token-head KV quantisation — superseded by a narrower PR; the INT2 half dropped',
  'u':['S4-ABANDONED-7','S4-ABANDONED-8'],
  'c':'PR closed unmerged by its own author in favour of #40835 (which merged). The companion PR #39074 was also closed unmerged with only bot text on the page.',
  'q':[R('S4-ABANDONED-7'),R('S4-ABANDONED-8')],
  'qlab':['on the companion PR #39074 the only stated text is the `mergify` bot notice']},
 {'sec':'C.1','h':'vLLM TurboQuant KV cache with PolarQuant + QJL — closed unmerged as a duplicate design',
  'u':['S4-ABANDONED-9'],'c':'closed unmerged by its author on a maintainer request; the QJL half did not survive into the shipped backend.',
  'q':[R('S4-ABANDONED-9')]},
 {'sec':'C.1','h':'vLLM’s first INT8 KV-cache-quantisation PR — closed without landing; the follow-up split PRs never landed either',
  'u':['S4-ABANDONED-15'],
  'c':'closed unmerged by a maintainer (`simon-mo`); the maintainer’s reason addresses W8A8/INT8 support generally, not KV quantisation specifically.',
  'q':[R('S4-ABANDONED-15')]},
 {'sec':'C.1','h':'vLLM CPU KV “swap space” — never allocated in V1, parameter removed; the abandonment PR was picked up by another author',
  'u':['S5-ABANDONED-1','S5-ABANDONED-2','S9-ABANDONED-2'],
  'c':'issue closed with the feature deleted: `--swap-space` and the `swap_space` field were removed by merged PR #36216. The original removal PR #27988 was closed unmerged and picked up by another author; the later per-layer `SwapConnector` revival (#35652) was closed unmerged by its author the day it opened, with no stated reason on the page.',
  'q':[R('S5-ABANDONED-1'),R('S5-ABANDONED-2')],
  'qlab':['the replacement PR #36216 records the abandonment'],
  'd':'#27984 opened 2025-11-03, closed 2026-03-07; #27988 opened 2025-11-03, closed 2026-03-07; #36216 merged 2026-03-07; #35652 opened and closed 2026-03-01'},
 {'sec':'C.1','h':'vLLM `Kvserve fusion` (KV compression + Mooncake connector) — 33 commits, never merged',
  'u':['S5-ABANDONED-9'],
  'c':'PR closed unmerged by maintainer `hmellor`; the only machine-recorded reason on the page is the `mergify` rebase request — no human maintainer rationale was posted.',
  'q':[T('This pull request has merge conflicts that must be resolved before it can be merged. Please rebase the PR, @VerrPower .')]},
 {'sec':'C.1','h':'vLLM `add KV cache tiering residency and lifecycle management` — self-closed as targeting the wrong repository',
  'u':['S5-ABANDONED-10'],'c':'PR closed unmerged by its own author, who renamed the title to record the reason.',
  'q':[R('S5-ABANDONED-10')]},
 {'sec':'C.1','h':'vLLM `Fail fast when CPU offload region exceeds available space` — closed because main already carried the fix',
  'u':['S5-ABANDONED-11'],'c':'PR closed unmerged by its own author as superseded by already-merged work (#50358, #48414, #52596).',
  'q':[R('S5-ABANDONED-11')]},
 {'sec':'C.1','h':'vLLM `Bypass power-of-2 rounding in KV offload CPU pinned allocation` — folded into a different PR',
  'u':['S5-ABANDONED-12'],
  'c':'PR closed unmerged “in #50094” by maintainer `orozery`; no prose rationale was posted. (The evidence file names the author as `woosebastian`; the verifier corrected this to `procr1337`.)',
  'w':'vLLM PR #48436, author procr1337 (verifier-corrected; `woosebastian` only cross-referenced the PR), closed by orozery',
  'q':[T('orozery closed this in #50094')]},
 {'sec':'C.1','h':'vLLM `SimpleCPUOffloadConnector` backlog bug report — closed by the fix PR, not as a duplicate',
  'u':['S5-ABANDONED-13'],
  'c':'closed as completed by PR #53532 (`stateReason: COMPLETED`, `duplicateOf: null`) — the evidence file’s “closed as duplicate” framing is contradicted by the page’s own structured data.',
  'q':[R('S5-ABANDONED-13')]},
 {'sec':'C.1','h':'vLLM DCP + FlashInfer MLA feature bundle — closed unmerged and split into smaller PRs',
  'u':['S8-ABANDONED-3','S12-ABANDONED-5'],
  'c':'PR closed unmerged by its own author after a maintainer asked for model evals and a reviewer asked for a split; the successor PRs #47541 and #47542 are open. The evidence file twice records this closure as “Breaking down to smaller PRs”.',
  'q':[R('S8-ABANDONED-3'),R('S12-ABANDONED-5')],
  'qlab':['the work items the closure dropped, from the PR body']},
 {'sec':'C.1','h':'vLLM layerwise KV transfer in P/D disaggregation — measured worse than bulk transfer, closed unmerged',
  'u':['S10-ABANDONED-1','S10-ABANDONED-2'],
  'c':'PR closed unmerged after its own author measured the layerwise method as slower; the roadmap item that tracked the same work was later closed `NOT_PLANNED`.',
  'q':[R('S10-ABANDONED-1'),R('S10-ABANDONED-2')],
  'qlab':['the roadmap entry that tracked it, verbatim'],
  'd':'PR created 2025-01-28, closed 2025-03-19; roadmap issue #10818 created 2024-12-02, closed not planned'},
 {'sec':'C.1','h':'vLLM Extensible (growable) KV cache — 39-commit series closed unmerged',
  'u':['S11-ABANDONED-51'],
  'c':'closed unmerged; the closure comment was retrieved by the verifier (“Replaced by …”) after the evidence file reported no justification text.',
  'q':[T('Replaced by https://github.com/vllm-project/vllm/pull/56492.')]},
 {'sec':'C.1','h':'vLLM host-resident KV cache offloading for sparse MLA decode — closed unmerged in favour of a parallel implementation',
  'u':['S11-ABANDONED-52'],
  'c':'closed unmerged; the author’s own closure rationale was retrieved by the verifier after the evidence file reported no retrievable reason.',
  'q':[T("Since this PR and @MatthewBonanni's PR #51323 implement the same feature … I find PR #51323 to be a better fit for the first version to be merged. Therefore, I plan to close this PR and continue optimizing this feature based on PR #51323.")]},
 {'sec':'C.1','h':'vLLM semantic checkpoints for recurrent-state prefix caching — `[Exp]` prototype closed unmerged',
  'u':['S11-ABANDONED-53'],
  'c':'closed unmerged; no explicit closure comment exists on the page (the verifier confirmed this row’s “reason not retrieved” is defensible).',
  'q':[R('S11-ABANDONED-53')]},
 {'sec':'C.1','h':'vLLM rejecting prefix caching for pooling / encoder-only models — sibling PR closed unmerged',
  'u':['S11-ABANDONED-54'],
  'c':'closed unmerged; no formal maintainer closure sentence exists, but a review comment on the page records the de-facto reason (the sibling PR #55159 targets the same function). The review comment is reproduced here exactly as the verification report renders it, including its ellipsis.',
  'q':[T('duplicates **#55159** … which targets the exact same function'),T('\\[Bugfix\\] Reject unsupported prefix caching for pooling models')],
  'qlab':['the commit subject of the closed PR itself']},
 {'sec':'C.1','h':'TensorRT-LLM Blackwell-native FlashInfer context attention — closed as relocated out of the repository',
  'u':['S11-ABANDONED-58'],'c':'closed as not planned — a relocation, not a technical rejection.',
  'q':[R('S11-ABANDONED-58')]},
 {'sec':'C.1','h':'TensorRT-LLM closed-unmerged PR — a closure reason does exist on the page',
  'u':['S11-ABANDONED-59'],
  'c':'closed unmerged by `yuxianq`; the verifier retrieved the closure comment after the evidence file asserted no reason existed (#18544 is merged). Concerns FMHA routing rather than strictly KV cache.',
  'q':[T('Close since we already have a bugfix PR https://github.com/NVIDIA/TensorRT-LLM/pull/18544')]},
 {'sec':'C.1','h':'vLLM unified `context_parallel_size` configuration/parallel-group design — superseded by the split PCP/DCP config',
  'u':['S12-ABANDONED-3','S12-ABANDONED-15'],
  'c':'PRs closed unmerged by a human maintainer (`hmellor`) with a technical supersede reason — a named-maintainer verdict rather than bot text or a stale timer.',
  'q':[R('S12-ABANDONED-15')],
  'd':'#26057/#26058 created 2025-10-01, closed 2026-03-06'},
 {'sec':'C.1','h':'vLLM MoRIIO multi-node TP16 prefill→decode KV dispatch — closed unmerged as superseded by three merged PRs',
  'u':['S12-ABANDONED-16'],
  'c':'PR closed unmerged; the closer comment is a human statement of supersession by #46116, #46115 and #47495.',
  'q':[R('S12-ABANDONED-16')],
  'd':'created 2026-06-11, final close ~2026-08-14 (#45228; companion #43063/#45230 quotes are sub-agent-retrieved)'},
 {'sec':'C.1','h':'TensorRT-LLM `Reuse V2 decode KV cache across turns` — closed unmerged by a maintainer as a deferral',
  'u':['S13-ABANDONED-2'],
  'c':'PR closed unmerged by a human Collaborator (`nvpohanh`) — a direct, deliberate abandonment of cross-turn decode-KV reuse in the V2 cache manager, phrased as “for now”.',
  'q':[R('S13-ABANDONED-2')]},
 {'sec':'C.1','h':'TensorRT-LLM inclusive host KV-cache tier (shadow reuse) — closed unmerged by its author after the reviewer never approved',
  'u':['S13-ABANDONED-12'],
  'c':'PR closed unmerged by its author. NO CLOSURE COMMENT WAS POSTED — the quoted maintainer line is the last substantive comment on the design, not a closure statement.',
  'q':[R('S13-ABANDONED-12')]},
 {'sec':'C.1','h':'SGLang Router — honoring KV-event storage tiers in the cache-aware tree (closed as superseded, then re-split)',
  'u':['S13-ABANDONED-13'],
  'c':'PR closed unmerged by its author as superseded; the same change was re-split into the stacked series #39108/#39109/#39110, all still open — the work moved rather than stopped.',
  'q':[R('S13-ABANDONED-13')]},
 {'sec':'C.1','h':'vLLM fine-grained prefix-cache hits for sliding-window groups — implementation closed unmerged twice by its own author',
  'u':['S2-ABANDONED-3'],
  'c':'both PRs (#54319 and its revision #54397) closed unmerged by their own author with no closure comment. The only retrievable statement of the blocking condition is an automated merge-conflict notice.',
  'q':[T('This pull request has merge conflicts that must be resolved before it can be merged. Please rebase the PR, @RichApple123 .'),R('S2-ABANDONED-3')],
  'qlab':['the design intent that is now unmerged, from the PR body']},
]
