# -*- coding: utf-8 -*-
# C.5 Negative results: measured, and it did not pay off (part 2)
from _gen_C_util import R, T
ITEMS5B = [
 {'sec':'C.5','h':'MLA’s shipped “MQA-absorb-only” decoding design does not pay off off-H100 (hardware coupling)',
  'u':['S6-ABANDONED-8'],
  'c':'paper concluding that the shipped MLA decode path is a regression relative to its own goals on non-H100 hardware — three coupled drawbacks: hardware coupling to H100, loss of head-axis tensor parallelism, and zero MTP gain on commodity inference GPUs.',
  'q':[R('S6-ABANDONED-8')],
  'd':'v1 submitted 14 May 2026; the 21 July 2026 revision is v3, not v2 (verifier correction).'},
 {'sec':'C.5','h':'FP8 KV cache and NVFP4 KV cache PRs on SM120 — measured slower, or unmerged with critical bugs',
  'u':['S6-ABANDONED-11'],
  'c':'VERIFIER CORRECTION: the abandonment premise is REFUTED — #41402 is CLOSED with `stateReason: COMPLETED` (not “closed without resolution”) and #41404 is a pull request, not an issue. The quoted third-party text is on an OPEN RFC page (#43235). The verifier also found the evidence file’s second quote misattributed: it comes from a ROCm/gfx950 (MI355X) report about `rope_kvcache` slowdowns, whose surrounding text says the opposite (“It was not a deadlock … a factor of 8 is indistinguishable from a hang from the outside”). What survives is the measured SM120 negative result quoted below.',
  'q':[T('MTP + TP>1 + concurrent>1 produces deadlocks (see #41402, #41404 — both closed without resolution).'),T('FP8 KV Cache is slower than BF16 on SM120 because there are no native FP8 block-scaled compute units. NVFP4 KV Cache PRs (#21601 in SGLang) remain unmerged with critical bugs.')],
  'qlab':['the same RFC page, on the FP8/NVFP4 paths (the evidence file’s third quotation, from issue #55687, is a different hardware stack and is dropped here per the verification report)'],
  'e':'READ BODY (verifier correction applied)'},
 {'sec':'C.5','h':'LMCache CacheBlend — non-prefix reuse decays back to the cold baseline under sustained novel RAG traffic',
  'u':['S11-ABANDONED-19','S7-ABANDONED-2'],
  'c':'closed as not planned by the issue author (comment “Closing here”, verifier-corrected) after the measured decay was reported: once L1 saturates, LRU evicts the warm document chunks and the speedup decays to ~1.0–1.1× within ~1–3 batches (~30–90 queries).',
  'q':[R('S11-ABANDONED-19')],
  'w':'`shawnguyen-tensormesh` (author and closer), LMCache issue #4663 (also filed as S7-ABANDONED-2)'},
 {'sec':'C.5','h':'DCPP (dynamic chunk resizing for chunked-prefill pipeline parallelism) — measured to LOSE at 512K',
  'u':['S8-ABANDONED-2'],
  'c':'paper concludes the technique does not pay off at long context: +10.5% compute, +36.1% exposed communication, 20.47 s residual bubble, a 4.6% TTFT regression and 4.4% throughput loss at 512K (it wins only in the 64K–256K band).',
  'q':[R('S8-ABANDONED-2')]},
 {'sec':'C.5','h':'Dropping a KV row and observing no accuracy loss as validation of an eviction policy — shown to be an unsound inference',
  'u':['S8-ABANDONED-6'],
  'c':'published negative result that undercuts the standard validation methodology of long-context KV eviction / episodic-memory designs; the paper also shows that YaRN position extension widens rather than closes the null.',
  'q':[R('S8-ABANDONED-6')]},
 {'sec':'C.5','h':'Final-answer accuracy as the metric for KV compression at long context — an asymmetric diagnostic; the “answer–evidence gap”',
  'u':['S8-ABANDONED-7','S14-ABANDONED-11'],
  'c':'published negative result whose own framing undercuts accuracy-only evaluation of long-context KV compression, including token-eviction families (H2O/SnapKV-class).',
  'q':[R('S8-ABANDONED-7')]},
 {'sec':'C.5','h':'Fixed-parameter eviction policies under workload mismatch — degrade by up to 2.7× (SAECache’s own comparison)',
  'u':['S9-ABANDONED-10'],
  'c':'published paper reporting that the fixed-parameter alternative degrades badly — a negative result about a whole class of KV eviction policies, stated by the authors.',
  'q':[R('S9-ABANDONED-10')]},
 {'sec':'C.5','h':'Dynamo KVBM 0.7.0 regression — TTFT 1.27 s → 8.23 s; worked around by the reporter, never fixed',
  'u':['S11-ABANDONED-14'],
  'c':'reported regression, worked around by the reporter (server-side flag change), not fixed. VERIFIER CORRECTION: the issue was created 2025-12-05, not 2025-12-17.',
  'q':[R('S11-ABANDONED-14')],
  'd':'reported 2025-12-05 (verifier-corrected; no 2025-12-17 activity exists on the page)'},
 {'sec':'C.5','h':'LMCache CPU offload measured as pure overhead next to vLLM’s own prefix cache',
  'u':['S11-ABANDONED-17'],
  'c':'closed `COMPLETED` — materially this is an explained-away negative result, not a fix: only 3 tokens were loaded from LMCache because vLLM’s prefix cache absorbed the hits, so the measurement was of LMCache overhead alone.',
  'q':[R('S11-ABANDONED-17')]},
 {'sec':'C.5','h':'LMCache’s reported 25× speedup was attributable to vLLM, not to LMCache CPU offload',
  'u':['S11-ABANDONED-18'],
  'c':'`NOT_PLANNED`, closed by the AUTOMATED STALE BOT. The negative result is in the issue body and the maintainer reply, not in the closure.',
  'q':[R('S11-ABANDONED-18')]},
 {'sec':'C.5','h':'LMCache token-dropping / compression accuracy is within run-to-run noise',
  'u':['S11-ABANDONED-25'],
  'c':'the PR merged, but its own documented measurement (accuracy carries ~1–2/30 run-to-run noise from decode non-determinism) undercuts the accuracy claim.',
  'q':[R('S11-ABANDONED-25')]},
 {'sec':'C.5','h':'vLLM FP8 KV-cache — the measured failure modes before the fixes, and the residual “when to avoid FP8” list',
  'u':['S11-ABANDONED-31'],
  'c':'published negative result, partially remediated; residual limits are documented in the blog’s own “When to Avoid FP8 KV-Cache” section (short contexts, head_dim 256 prefill, 91%→13% NIAH at 128k on Hopper before the fix, gpt-oss-20b break-even beyond 700k tokens).',
  'q':[R('S11-ABANDONED-31')],
  'approx':True},
 {'sec':'C.5','h':'Seven curated KV-compression mechanisms all rejected under a pre-registered protocol at matched mean cache',
  'u':['S11-ABANDONED-36'],
  'c':'published negative result (pre-registered protocol, held-out confirmation) on long-form mathematical reasoning with two distilled-reasoning models at budgets b ∈ {64, 128}.',
  'q':[R('S11-ABANDONED-36')]},
 {'sec':'C.5','h':'Mixed-precision KV bit allocation can be worse than uniform quantisation — “distortion model mismatch”',
  'u':['S11-ABANDONED-39'],
  'c':'published negative result about the popular technique; the paper’s own contribution is the fix. Applying one quantiser’s distortion model to another inverts the allocation order.',
  'q':[R('S11-ABANDONED-39')]},
 {'sec':'C.5','h':'Per-layer FP8 KV-quantisation error attribution is non-diagnostic — errors survive on cross-layer cancellation',
  'u':['S11-ABANDONED-40'],
  'c':'published negative result: in a 28-layer sweep no single layer’s pollution alone loses anything (0/28).',
  'q':[R('S11-ABANDONED-40')]},
 {'sec':'C.5','h':'Per-layer eviction routing has null results on short inputs (MATH-500, LongBench TREC)',
  'u':['S11-ABANDONED-41'],
  'c':'published negative results, self-labelled “null results”: the solver picks keep=1.0 on most layers for short inputs, cleanly characterising when per-layer routing has headroom to help.',
  'q':[R('S11-ABANDONED-41')]},
 {'sec':'C.5','h':'Sliding window is order-optimal among suffix-only cache policies — a negative result bounding a whole policy class',
  'u':['S11-ABANDONED-42'],
  'c':'published negative result bounding the suffix-only policy class; whether recurrent or propagating cache summaries can beat the scaling is left open by the authors.',
  'q':[R('S11-ABANDONED-42')],
  'approx':True},
 {'sec':'C.5','h':'The standard chunked-mean fast-weight write is silently wrong — C²−C spurious cross-token outer products per chunk',
  'u':['S11-ABANDONED-43'],
  'c':'published negative result about a widely used approximation.',
  'q':[R('S11-ABANDONED-43')],
  'approx':True},
 {'sec':'C.5','h':'Prefetching cannot hide CPU-offload transfers — PCIe-bandwidth bound, not prediction-quality bound (WiSP)',
  'u':['S11-ABANDONED-45'],
  'c':'published negative result explicitly about a “natural next step”: speculative transfers compete with demand transfers instead of hiding them. (Scope caveat from the evidence: the mechanism concerns experts, not KV.)',
  'q':[R('S11-ABANDONED-45')]},
 {'sec':'C.5','h':'Three attempts to beat LRU for cross-request KV prefix caching all failed on 68,266 real Claude Code requests plus 23,608 Mooncake requests',
  'u':['S11-ABANDONED-46'],
  'c':'published null result on real traces; the leaf restriction both major engines implement bought 0.02pp on this workload. The author also documents a harness trap (an offline Belady oracle losing to LRU).',
  'q':[R('S11-ABANDONED-46')]},
 {'sec':'C.5','h':'vLLM’s own docs state that disaggregated prefill DOES NOT improve throughput',
  'u':['S12-ABANDONED-12'],
  'c':'shipped feature with an explicit negative scope statement in the project’s own documentation — the technique is published and supported, but the headline benefit is disclaimed.',
  'q':[R('S12-ABANDONED-12')]},
 {'sec':'C.5','h':'“Beyond the Buzz: A Pragmatic Take on Inference Disaggregation” — disaggregation is not a universal solution',
  'u':['S12-ABANDONED-13'],
  'c':'published negative/limiting result — the paper’s headline finding undercuts multi-node disaggregation for a large part of the design space.',
  'q':[R('S12-ABANDONED-13')]},
 {'sec':'C.5','h':'Prefix caching for small reasoning models — measured to make 7B serving WORSE',
  'u':['S13-ABANDONED-3'],
  'c':'published empirical study whose own experiments conclude the technique does not pay off in the 7B regime (increased latency).',
  'q':[R('S13-ABANDONED-3')]},
 {'sec':'C.5','h':'Immediate online KV compaction for agents hurts performance; delaying compaction recovers much of the gap',
  'u':['S13-ABANDONED-5'],
  'c':'published empirical study whose headline result is that the naive (immediate) form of the technique hurts — the negative finding is the paper’s main contribution.',
  'q':[R('S13-ABANDONED-5')]},
 {'sec':'C.5','h':'Learned importance scoring for KV compression does not beat random selection',
  'u':['S13-ABANDONED-14'],
  'c':'published negative result — the paper’s own headline is that the learned scorer fails across 5 seeds, 4 retention levels and 3 tasks.',
  'q':[R('S13-ABANDONED-14')],
  'w':'Brady Steele — “On the Limits of Learned Importance Scoring for KV Cache Compression” (the lead-author name was not independently confirmed by the verifier; the title and abstract quotes were)'},
 {'sec':'C.5','h':'Nexus — the off-anchor KV splice boundary, and a drift gate that does not predict drift',
  'u':['S13-ABANDONED-15'],
  'c':'published paper containing two explicit self-declared negative results that bound the technique; the KV-splice lever is the bounded part.',
  'q':[R('S13-ABANDONED-15')]},
 {'sec':'C.5','h':'Permanent eviction for reasoning chain-of-thought is catastrophic (accuracy 0–2.5%), and the reproduced SOTA eviction method lands at 0–32%',
  'u':['S13-ABANDONED-17'],
  'c':'published negative result about the dominant approach, plus a failed reproduction of the then-SOTA eviction method.',
  'q':[R('S13-ABANDONED-17')]},
 {'sec':'C.5','h':'Query-aware KV-compression evaluation — the pay-off does not survive a matched-budget audit; SnapKV loses to a trivial baseline',
  'u':['S14-ABANDONED-10'],
  'c':'published negative result: under the query-agnostic protocol only KeyDiff consistently beats a best-of-3 trivial baseline, and the most widely deployed method (SnapKV) loses to “keep the start and the recent window” on average (−0.066).',
  'q':[R('S14-ABANDONED-10')]},
]
