# -*- coding: utf-8 -*-
# C.4 Reverted, withdrawn, or retracted by the author
from _gen_C_util import R, T
ITEMS4 = [
 {'sec':'C.4','h':'vLLM `--prefix-match-unit` documentation issue — withdrawn by its own author',
  'u':['S1-ABANDONED-1'],
  'c':'closed as not planned (`stateReason=NOT_PLANNED`) by the author himself, not a maintainer and not a bot.',
  'q':[T('Closing this. The premise was wrong and the remaining justification did not survive checking either --prefix-match-unit exists, it does what I said could not be done, and it is documented …')],
  'd':'created 2026-08-31, closed 2026-09-01'},
 {'sec':'C.4','h':'vLLM equal-block-sizes hybrid crash report — retracted by its author as a duplicate with a wrong premise',
  'u':['S1-ABANDONED-2'],
  'c':'closed as not planned (`stateReason=NOT_PLANNED`); the title itself reads “RETRACTED — duplicate of #53142 (my \\"equal block sizes\\" premise was wrong; see closing comment)”. Closed by the author.',
  'q':[R('S1-ABANDONED-2')]},
 {'sec':'C.4','h':'Attempted revert of the HMA GPU-side KV events feature — the revert PR itself was closed unmerged',
  'u':['S1-ABANDONED-8'],
  'c':'PR closed unmerged (`state=CLOSED`, `mergedTime=null`, `mergedBy=null`); the target feature PR #37688 remains MERGED. No human closure comment was retrievable — the only verbatim artifact is the commit message.',
  'q':[T('This reverts commit cc07dad789e9ae3f02ab6a4794800b8c1cc240c6.')],
  'd':'created 2026-04-13, closed 2026-05-20'},
 {'sec':'C.4','h':'A publicised “92.5% prompt-throughput collapse” and “memory paradox” for q4_0 KV — retracted by its own author',
  'u':['S4-ABANDONED-6'],
  'c':'self-retraction — the measurement that made q4_0 KV look catastrophic was wrong (RSS measurement, silent request failures); the corrected numbers reverse the conclusion.',
  'q':[R('S4-ABANDONED-6')]},
 {'sec':'C.4','h':'SGLang MERGED REVERT of the `kv_cache_scheme` refactor for quantisation — it broke DeepSeek V3 FP4',
  'u':['S4-ABANDONED-11'],'c':'MERGED REVERT — the revert landed; the refactor was undone.',
  'q':[R('S4-ABANDONED-11')]},
 {'sec':'C.4','h':'Custom evictor implementations for the vLLM filesystem offload tier — withdrawn by the author as codebase pollution; the follow-up capacity-bound LRU attempt also closed unmerged',
  'u':['S5-ABANDONED-21','S9-ABANDONED-3'],
  'c':'both PRs CLOSED unmerged by their own authors. The first has a verbatim reason; for the second (#52784) the page contains no closing comment — the last substantive content is Copilot’s automated review raising an eviction-never-triggers bug.',
  'q':[R('S5-ABANDONED-21'),R('S9-ABANDONED-3')],
  'qlab':['the second attempt (#52784), whose evidence that the first was abandoned is recorded in its body'],
  'd':'#43725 created 2026-05-27, closed 2026-06-24; #52784 created 2026-08-18, closed 2026-08-19'},
 {'sec':'C.4','h':'Dynamo progressive decode-affinity yield under KV pressure — author closed it after finding the existing soft-affinity support gave the same gain',
  'u':['S7-ABANDONED-8'],
  'c':'PR closed unmerged by its author (human reason, not a bot): the same performance improvement was already available via soft affinity.',
  'q':[R('S7-ABANDONED-8')]},
 {'sec':'C.4','h':'vLLM PoC “soft-pin recently-hit prefix-cache entries” — closed by the author as a workaround that would not fix the real bug',
  'u':['S9-ABANDONED-4','S14-ABANDONED-4'],
  'c':'PR closed unmerged by the author (human, not a bot; not a maintainer decision), explicitly to avoid leaving a workaround in the review queue. (The S14 duplicate row for the same closure is merged here; its copy of the comment dropped the closing lines, the S9 copy is complete.)',
  'q':[R('S9-ABANDONED-4')]},
 {'sec':'C.4','h':'vLLM popular-insert extension of the soft-pin — closed as superseded, and the superseding measurement later failed independent reproduction',
  'u':['S9-ABANDONED-5','S14-ABANDONED-5'],
  'c':'PR closed unmerged by the author as superseded by #43302.',
  'q':[R('S14-ABANDONED-5')]},
 {'sec':'C.4','h':'vLLM ARC eviction for the GPU block pool, first attempt — closed by its author for a procedural reason and reopened as #27039',
  'u':['S9-ABANDONED-8'],
  'c':'CLOSED unmerged by the author (human) for a procedural reason, 7 minutes before reopening as #27039 (which merged).',
  'q':[R('S9-ABANDONED-8')]},
 {'sec':'C.4','h':'vLLM attention-sink-protected eviction policy request — withdrawn by its author after a collaborator’s clarification',
  'u':['S9-ABANDONED-9'],
  'c':'CLOSED (completed) by the issue author himself after a collaborator’s clarification — a withdrawn request, not a maintainer rejection.',
  'q':[R('S9-ABANDONED-9')]},
 {'sec':'C.4','h':'Dynamo KVBM V2 transfer — merged revert, removing `BlockTransferHandlerV2` from the public API',
  'u':['S11-ABANDONED-6'],
  'c':'MERGED REVERT (`state=MERGED`, `mergedTime=2026-01-13T22:18:07Z`). The diff removes `BlockTransferHandlerV2` from the public API surface.',
  'q':[R('S11-ABANDONED-6')]},
 {'sec':'C.4','h':'Dynamo KVBM documentation claimed tiers and knobs that do not exist — correction PRs opened to retract the claims',
  'u':['S11-ABANDONED-16'],
  'c':'documentation/claim retraction: the advertised capabilities were never implemented; the correction PRs #14012 and #14011 were open at retrieval (a counter-PR #13867 also exists).',
  'q':[R('S11-ABANDONED-16')]},
 {'sec':'C.4','h':'LMCache merged revert of its MP adapter shim',
  'u':['S11-ABANDONED-23'],'c':'merged revert, 2026-04-23.',
  'q':[R('S11-ABANDONED-23')]},
 {'sec':'C.4','h':'SGLang AMD DeepSeek-V4 unified-KV pool sizing — merged revert, then relitigated and relanded the next day with gating',
  'u':['S11-ABANDONED-50'],
  'c':'MERGED REVERT (`state=MERGED`, `mergedTime=2026-09-06T00:28:47Z`); the change was relanded the next day by PR #38192 with gating. No narrative reason was retrievable in the revert PR (PR comment bodies did not render for the evidence agent).',
  'q':[R('S11-ABANDONED-50')]},
 {'sec':'C.4','h':'TensorRT-LLM merged revert of the FlashInfer→CuTeDSL MLA backend path about two weeks after it landed',
  'u':['S11-ABANDONED-56'],
  'c':'MERGED REVERT (`state=MERGED`, `mergedTime=2026-09-08T08:29:00Z`), preserving the standalone CuTeDSL FMHA backend and later changes.',
  'q':[R('S11-ABANDONED-56')]},
 {'sec':'C.4','h':'SGLang zigzag prefill context parallelism — withdrawn (“temporarily unavailable”) for every current DeepSeek/GLM model',
  'u':['S12-ABANDONED-11'],
  'c':'feature disabled / withdrawn at the documentation level — a shipped technique pulled for the models that most need it, replaced by `interleave` with `--dp 1`. Not a PR closure. The quoted text lives in the SGLang cookbook pages; VERIFIER NOTE: the row’s headline DCP page does not contain the word “zigzag”, so the sourcing is imprecise.',
  'q':[R('S12-ABANDONED-11')],
  'd':'docs current in the retrieved SGLang tree (2026-09); line numbers in the evidence file are from a local checkout and are not reproduced here'},
 {'sec':'C.4','h':'vLLM revert of “[Nixl][PD] DCP support for MLA models” after it broke DeepSeek-V4-Flash — the revert PR was itself closed unmerged in favour of a narrower fix',
  'u':['S12-ABANDONED-17'],
  'c':'revert PR closed unmerged; the narrower fix #54400 was merged the same day. The substantive reason is a human/automated-agent technical statement in the PR body, not a stale timer.',
  'q':[R('S12-ABANDONED-17')]},
 {'sec':'C.4','h':'vLLM ACE — Attention-Weighted Context Eviction for multi-turn agentic tool results — withdrawn by its own author after benchmarking',
  'u':['S13-ABANDONED-1'],
  'c':'PR closed UNMERGED by the author after a self-run benchmark; the author states the design lost to doing nothing. Not stale-bot, not maintainer-closed — an author withdrawal with measured data.',
  'q':[R('S13-ABANDONED-1')]},
 {'sec':'C.4','h':'SGLang stripping the Anthropic billing header so Claude Code turns can share a prefix — closed unmerged by its author',
  'u':['S13-ABANDONED-6'],
  'c':'PR closed UNMERGED by the author (joninco closed this May 10, 2026); no maintainer merge, the fix did not land.',
  'q':[R('S13-ABANDONED-6')]},
 {'sec':'C.4','h':'vLLM auto-revert of “[Mamba] enable prefix cache by default” — the revert PR was closed unmerged in favour of the forward fix',
  'u':['S13-ABANDONED-7'],
  'c':'revert PR closed UNMERGED (`mergedTime` null; “noooop closed this Aug 5, 2026”). The underlying failures were real and are recorded verbatim.',
  'q':[R('S13-ABANDONED-7')]},
 {'sec':'C.4','h':'vLLM multi-storage replication for shared-prefix KV blocks — closed by its author after an independent test showed it was a regression',
  'u':['S14-ABANDONED-6'],
  'c':'PR closed unmerged by the author. The failure was caught by an independent reproduction (`stecasta`), not by the author’s own benchmark: 0% hit rate and +10–13% wall time versus the no-cache baseline.',
  'q':[R('S14-ABANDONED-6')]},
]
