# -*- coding: utf-8 -*-
# C.5 Negative results: measured, and it did not pay off (part 1)
from _gen_C_util import R, T
ITEMS5 = [
 {'sec':'C.5','h':'Elastic KV cache — reclaiming the prefill-activation reserve; built, measured, and reported as a negative result',
  'u':['S2-ABANDONED-8','S13-ABANDONED-4','S9-ABANDONED-1'],
  'c':'published negative result — the mechanism was built and explicitly judged not to pay off (the penalty the premise requires is ~1% between chunk sizes of 8192 and 32768; simply lowering `max_num_batched_tokens` recovers more KV).',
  'q':[R('S9-ABANDONED-1')]},
 {'sec':'C.5','h':'External/NVMe KV caching falls below break-even on a fast GPU — the authors’ own admission rule',
  'u':['S2-ABANDONED-9','S11-ABANDONED-44','S13-ABANDONED-18','S5-ABANDONED-8'],
  'c':'published negative/limiting result for the cross-tier direction on fast hardware: external KV caching should be treated as a per-setup admission decision, not a general win.',
  'q':[R('S2-ABANDONED-9'),R('S5-ABANDONED-8')],
  'qlab':['the same paper’s break-even and below-8k findings (the S5 row’s quotation had dropped the word “as”; corrected here)'],
  'w':'Joseph Kanichai, Tiziano De Matteis, Animesh Trivedi — “Building py-kvcache: A Performance Characterization of External KV Caching for vLLM with NVMe SSDs” (arXiv 2609.11744); also carried as S11-ABANDONED-44, S13-ABANDONED-18 and S5-ABANDONED-8'},
 {'sec':'C.5','h':'Exact composition of all cached recurrent states for hybrid prefix reuse — unnecessary and, on some architectures, harmful',
  'u':['S2-ABANDONED-10'],'c':'published negative result against a specific competing technique (exact state composition, attributed to concurrent work HYPIC) inside the hybrid prefix-caching design space.',
  'q':[R('S2-ABANDONED-10')]},
 {'sec':'C.5','h':'Repairing reused KV for non-prefix positions is often worse than not reusing at all (KVShareArena)',
  'u':['S2-ABANDONED-11'],
  'c':'published negative result about the value of KV reuse outside the exact-prefix case, including a negative result for cache compression on agent reports and for trained adapters across checkpoints.',
  'q':[R('S2-ABANDONED-11')]},
 {'sec':'C.5','h':'Attention-score KV eviction — the selection signal contributes almost nothing (Random Attention)',
  'u':['S3-ABANDONED-10','S11-ABANDONED-35'],
  'c':'published negative result against the whole scored-selection family (H2O/SnapKV/Ada-KV/TriAttention-style scoring): random eviction within each head matches the strongest prior evictor while serving 32–43% higher throughput.',
  'q':[R('S3-ABANDONED-10')]},
 {'sec':'C.5','h':'“Protection Is (Nearly) All You Need” — structural protection dominates scoring; H2O/SnapKV/StreamingLLM/Ada-KV/QUEST collapse without it',
  'u':['S3-ABANDONED-11','S11-ABANDONED-37','S11-ABANDONED-38'],
  'c':'published negative result: seven policies collapse to near-zero quality without structural protection, and with protection the simplified score-isolation variants are TOST-equivalent to LRU. Linear online credit estimation adds nothing (the paper’s own §8 “Negative Result”).',
  'q':[R('S3-ABANDONED-11'),R('S11-ABANDONED-37')],
  'qlab':['the paper’s explicit §8 negative result on learned credit estimation'],
  'approx':True},
 {'sec':'C.5','h':'Rate–distortion survey — attention-magnitude/recency retention signals fail uniformly and irreversibly, and repeated agent compaction is almost never measured',
  'u':['S3-ABANDONED-12'],
  'c':'published negative characterisation across four research communities; the paper turns the observation into a benchmark proposal rather than a fix.',
  'q':[R('S3-ABANDONED-12')]},
 {'sec':'C.5','h':'VarRate — SnapKV/Ada-KV-style token selection collapses 11–15 points under query-agnostic reuse',
  'u':['S3-ABANDONED-13'],
  'c':'published negative result on irreversible eviction, specifically naming SnapKV and Ada-KV; the paper abandons eviction in favour of rank allocation.',
  'q':[R('S3-ABANDONED-13')]},
 {'sec':'C.5','h':'“More GPUs or a Smaller Cache?” — no cost-equivalence crossover found; extra GPUs are largely wasted spend below a model-size wall',
  'u':['S3-ABANDONED-14'],
  'c':'published negative result against the “add tensor parallelism instead of compressing the cache” answer to KV memory pressure (compression cheaper by 1.20×–2.00×; crossover at roughly 36B parameters on an 80 GB card).',
  'q':[R('S3-ABANDONED-14')]},
 {'sec':'C.5','h':'VaSE — eviction often yields worse accuracy than selection-based sparse attention; a few large-magnitude value states cause catastrophic failure when evicted',
  'u':['S3-ABANDONED-15'],
  'c':'published negative result on the eviction-vs-full-cache trade-off, plus a documented failure mode of magnitude-agnostic scoring.',
  'q':[R('S3-ABANDONED-15')]},
 {'sec':'C.5','h':'QJL residual correction / TurboQuantProd keys — rejected on independent measurement; MSE beats the paper’s recommended Prod path',
  'u':['S4-ABANDONED-2','S4-ABANDONED-14'],
  'c':'technique rejected after measurement: the reproduction concludes the paper’s recommended Prod path should not be used for attention, with the variance cost quantified. VERIFIER CORRECTION: the first quoted fragment in the S4-ABANDONED-14 row was posted by `Arclabs001`, not by `scos-lab`; only the second fragment is scos-lab’s.',
  'w':'scos-lab (`turboquant` reference implementation README) and `Arclabs001` in the ggml-org/llama.cpp discussion #20969 (verifier-corrected authorship)',
  'q':[R('S4-ABANDONED-2'),R('S4-ABANDONED-14')],
  'qlab':['the quantified variance finding in the same thread']},
 {'sec':'C.5','h':'vLLM’s own comprehensive evaluation concludes TurboQuant k8v4 is not worth using and the aggressive presets are unfit for production',
  'u':['S4-ABANDONED-4'],
  'c':'published negative result from the project that shipped the technique — the maintainers’ own recommendation is to prefer FP8 and avoid the aggressive presets.',
  'q':[R('S4-ABANDONED-4')]},
 {'sec':'C.5','h':'turbo3/turbo4 KV cache types judged worse than plain q4_0 on perplexity over all of wiki.test.raw',
  'u':['S4-ABANDONED-5'],
  'c':'community measurement reporting the new format loses to an existing simpler format — no adoption followed. VERIFIER CORRECTION: the post is by `ubergarm` (who opens with “@Dampfinchen”), not by Dampfinchen.',
  'w':'`ubergarm`, in the ggml-org/llama.cpp discussion #20969 (verifier-corrected authorship; the evidence file named the addressee)',
  'q':[R('S4-ABANDONED-5')]},
 {'sec':'C.5','h':'TurboQuant’s advertised sub-4-bit compression does not survive per-block metadata on a real 27B hybrid model',
  'u':['S4-ABANDONED-16'],
  'c':'measured shortfall against the advertised ratio (2.75× at 256K instead of the ≈5× full-bit-rate ratio; ~6 bits/element once per-block norms are counted), plus a demonstration that MTP consumes the freed headroom.',
  'q':[R('S4-ABANDONED-16')]},
 {'sec':'C.5','h':'turbo3 V-cache degrades generation-trajectory scores badly even when output-level smoke tests look clean',
  'u':['S4-ABANDONED-17'],
  'c':'measured decode-path divergence from the f16 reference that output-level smoke tests do not detect (the gap grows with model size and quantisation aggressiveness).',
  'q':[R('S4-ABANDONED-17')]},
 {'sec':'C.5','h':'GPUDirect Storage (cuFile/KvikIO) prototype for KV cache — slower than every other implementation tested',
  'u':['S5-ABANDONED-4'],
  'c':'negative result in a published paper — the authors built the GDS prototype and rejected it.',
  'q':[R('S5-ABANDONED-4')]},
 {'sec':'C.5','h':'io_uring / xNVMe / SPDK userspace NVMe paths did not improve end-to-end TTFT',
  'u':['S5-ABANDONED-5'],
  'c':'negative result in a published paper — the faster I/O engines improved synthetic microbenchmarks but not vLLM TTFT, so they were dropped from the final design.',
  'q':[R('S5-ABANDONED-5')]},
 {'sec':'C.5','h':'llm-d’s filesystem KV cache was deprecated mid-experiment and its staging allocation caused ~2.3× data amplification',
  'u':['S5-ABANDONED-7','S5-ABANDONED-6'],
  'c':'negative result plus upstream deprecation in a published paper; the standalone FS connector reached a final release and is now upstreamed into vLLM as the FS tier of the multi-tier offloading connector.',
  'q':[R('S5-ABANDONED-7'),R('S5-ABANDONED-6')],
  'qlab':['the llm-d README’s own sunset/upstream note'],
  'w':'t348575 et al., py-kvcache (arXiv 2609.11744) §3.2/§5.1; llm-d project (`llm-d/llm-d-kv-cache`)'},
 {'sec':'C.5','h':'SSD-backed KV cache restore is “no longer beneficial” on modern engines, and GPU Direct Storage does not rescue it (Tutti’s own measurements)',
  'u':['S5-ABANDONED-15','S5-ABANDONED-14','S14-ABANDONED-12'],
  'c':'negative results inside a published paper — SSD restore loses to DRAM (GPU bubbles >70%, ~80% with layer-wise transfers), GDS still relies on CPU intervention and leaves GPU bubble time above 70%; the paper reports a 98.3% hit-rate crossover below which the SSD tier is not beneficial.',
  'q':[R('S5-ABANDONED-15'),R('S5-ABANDONED-14')],
  'qlab':['the same paper’s GDS verdict in §2.2'],
  'w':'Tutti authors (arXiv 2605.03375) — the S14 row for the same finding had no quote of its own and is merged here'},
 {'sec':'C.5','h':'Multi-SSD KV offloading collapses to the baseline on a single SSD (Swarm)',
  'u':['S5-ABANDONED-16'],
  'c':'the paper’s own scaling result — no benefit in the single-device configuration, which is exactly the single-node single-local-disk case.',
  'q':[R('S5-ABANDONED-16')]},
 {'sec':'C.5','h':'KV offloading degrades accuracy on context-intensive tasks (Yandex) — low-rank projection of keys and unreliable landmarks',
  'u':['S5-ABANDONED-17'],
  'c':'negative empirical result in a published paper (significant degradation on both Llama 3 and Qwen 3); the authors nonetheless argue the technique is salvageable with better compression and key selection.',
  'q':[R('S5-ABANDONED-17')]},
 {'sec':'C.5','h':'KV offload to host DRAM is memory-bound by construction on typical workloads — 99% of latency spent on transfers, GPUs at 28% of rated TDP',
  'u':['S5-ABANDONED-18'],
  'c':'negative analytic + empirical result in a published paper: typical workloads exceed the critical cached-to-prefill token ratio by orders of magnitude.',
  'q':[R('S5-ABANDONED-18')]},
 {'sec':'C.5','h':'HERALD’s own measurement — host-memory KV fetch overtakes the forward pass at 8K context (3.12× slower; 7.61× at 32K)',
  'u':['S5-ABANDONED-19'],
  'c':'the paper’s own negative characterisation of the PCIe tier, which is why it abandons per-step full-cache fetching.',
  'q':[R('S5-ABANDONED-19')]},
 {'sec':'C.5','h':'Performing attention on the CPU in KV-offload systems is argued to be on the wrong side of the roofline (KVDrive)',
  'u':['S5-ABANDONED-20'],
  'c':'published rebuttal of a design family (“prior works advocate performing attention on the CPU in KV cache offloading systems”) — the paper argues that regime is bandwidth-roof-bound.',
  'q':[R('S5-ABANDONED-20')],
  'approx':True},
 {'sec':'C.5','h':'SVD/low-rank compression of attention projections accelerates rank collapse on pretrained models (negative original finding)',
  'u':['S6-ABANDONED-4'],
  'c':'paper reporting an explicitly negative original finding that undercuts the standard motivation for SVD-based KV/attention projection compression.',
  'q':[R('S6-ABANDONED-4')]},
 {'sec':'C.5','h':'Pure low-rank (Tucker/SVD) KV backbones are insufficient on the value spectrum and degrade sharply past ~4×',
  'u':['S6-ABANDONED-5'],
  'c':'paper finding that the low-rank-only variant does NOT pay off (it needs a quantised residual to be near-lossless), with downstream collapse documented (LLaMA GSM8K 18.5%/6.0%/1.5% at 4×/6×/8×).',
  'q':[R('S6-ABANDONED-5')],
  'approx':True},
 {'sec':'C.5','h':'Low-rank KV compression on the target model class — keys compress, values do not; Qwen3-4B is the sensitive case',
  'u':['S6-ABANDONED-6'],
  'c':'benchmark finding that limits low-rank KV compression and specifically flags Qwen3-4B as substantially more sensitive than LLaMA-2-7B; the authors conclude future compression must be layer-aware.',
  'q':[R('S6-ABANDONED-6')]},
 {'sec':'C.5','h':'Post-training SVD of projection weights for KV savings — achievable compression is bounded, and compressing Q and K together is catastrophic',
  'u':['S6-ABANDONED-7'],
  'c':'paper concluding the retraining-free variant does NOT pay off beyond moderate ratios (K-only SVD at rank 192 degrades by 26%), while the obvious stronger form destroys attention patterns.',
  'q':[R('S6-ABANDONED-7')],
  'd':'v1 submitted 16 Feb 2026; announced March 2026; the 28 March 2026 revision is v4, not v2 (verifier correction).'},
] 
